### ISSUE TITLE
有没有WINDOWS版本的？

### ISSUE THREAD

**Issue by yaonizui** [zhangn1985/you-get#14]
请问有WINDOWS版本吗？想在WIN下使用

**Comment by zhangn1985** [comment]
我目前在做code refactor，所以目前这个算比较低优先级。
不过我先记住了你的需求。如果你等不及可以自行下载python3来运行程序。

**Comment by yaonizui** [comment]
希望能有WINDOWS版本。方便不会用python3的小伙伴吗？感谢了

**Comment by zhangn1985** [comment]
1，cx_Freeze我安装失败。
2，py2exe需要win32环境，而我没有。
3，作为一个fork，发布binary不太好。
